//created on: Dec 3, 2015
package com.redhat.rules;

//list any import classes here.
import com.redhat.drools.camel.model.MyModelObj;
import com.redhat.drools.camel.model.MyOtherModelObj;

//declare any global variables here

rule "Most People are Normal"
	salience -100
    when
        not( exists MyOtherModelObj() )
        MyModelObj( $value : value )
    then
        insert( new MyOtherModelObj( $value, "Normal" ) );
end

rule "Michael is awesome"
	when
		MyModelObj( $value : value, value == "Michael" )
	then
		insert( new MyOtherModelObj( $value, "Awesome" ) );
end

