//created on: Dec 3, 2015
package com.redhat.rules;

//list any import classes here.
import com.redhat.drools.camel.model.MyModelObj;
import com.redhat.drools.camel.model.MyOtherModelObj;

//declare any global variables here

rule "Your First Rule"
    when
        MyModelObj( $value : value, $number : number )
    then
        insert( new MyOtherModelObj( $value ) );
end

rule "Michael is awesome"
	when
		MyModelObj( $value : value, $number : number, value == "Michael" )
	then
		System.out.println( "Here" );
		insert( new MyOtherModelObj( $value, $number * 100 ) );
end

rule "Goldsmith is not"
	when
		MyModelObj( $value : value, $number : number, value == "Goldsmith" )
	then
		System.out.println( "Here" );
		insert( new MyOtherModelObj( $value, $number * -100 ) );
end
		