//created on: Dec 3, 2015
package com.redhat.rules;

//list any import classes here.
import com.redhat.drools.camel.model.MyModelObj;
import com.redhat.drools.camel.model.MyOtherModelObj;

//declare any global variables here

rule "Most People are Neutral"
	salience -100
    when
    	not( exists MyOtherModelObj() )
        MyModelObj( $value : value )
    then
        insert( new MyOtherModelObj( $value, "Default" ) );
end

rule "Michael is awesome"
	when
		MyModelObj( $value : value, value == "Michael" )
	then
		System.out.println( "Here" );
		insert( new MyOtherModelObj( $value, "Awesome" ) );
end

rule "Goldsmith is not"
	when
		MyModelObj( $value : value, value == "Goldsmith" )
	then
		System.out.println( "Here" );
		insert( new MyOtherModelObj( $value, "Not Awesome" ) );
end
		