//created on: Dec 3, 2015
package com.redhat.rules;

//list any import classes here.
import com.redhat.drools.camel.model.MyModelObj;
import com.redhat.drools.camel.model.MyOtherModelObj;

//declare any global variables here




rule "Your First Rule"
    when
        MyModelObj()
    then
        System.err.println( "here" );

end

/**
rule "Test"
    when
        $o : Object()
    then
        System.err.println( $o.getClass() );
end
*/